Document: rtags
Title: Debian rtags Manual
Author: <insert document author here>
Abstract: This manual describes what rtags is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rtags/rtags.sgml.gz

Format: postscript
Files: /usr/share/doc/rtags/rtags.ps.gz

Format: text
Files: /usr/share/doc/rtags/rtags.text.gz

Format: HTML
Index: /usr/share/doc/rtags/html/index.html
Files: /usr/share/doc/rtags/html/*.html
